[workspace]

members = [
    "winfsp-rs/ptfs-winfsp-rs",
    "winfsp-rs/ntptfs-winfsp-rs",
    "winfsp-rs/winfsp",
    "winfsp-rs/winfsp-sys",
    "snowflake-projfs",
    "snowflake-projfs-common",
    "snowflake-projfs-fsp",
]
